USE LBDT_G01;

If  exists 
 (Select *
   From  sys.check_constraints
   Where object_id  =  OBJECT_ID(N'dbo.CK_G01_P02_FUNCIONARIOS_SUPERVISOR') 
     and parent_object_id = OBJECT_ID(N'dbo.G01_P02_FUNCIONARIOS_SUPERVISOR'))
   ALTER TABLE  dbo.G01_P02_FUNCIONARIOS_SUPERVISOR
      DROP CONSTRAINT CK_G01_P02_FUNCIONARIOS_SUPERVISOR;
IF  EXISTS
  (select *
    From  sys.objects
    Where object_id = OBJECT_ID(N'dbo.G01_P02_FUNCIONARIOS_SUPERVISOR') 
      and type in (N'U'))
   DROP TABLE dbo.G01_P02_FUNCIONARIOS_SUPERVISOR;

CREATE TABLE dbo.G01_P02_FUNCIONARIOS_SUPERVISOR (
  codigo            numeric (3, 0)  NOT NULL ,
 
CONSTRAINT PK_G01_P02_FUNCIONARIOS_SUPERVISOR PRIMARY KEY CLUSTERED 
   (codigo  asc)
   WITH
    FILLFACTOR = 10,

);